title: "My Tailwind Exercise"
description: "A simple Jekyll site with Tailwind CSS"
baseurl: "/tailwind_exercise"  # Important! Use your repo name
url: "https://sender0012.github.io"  

postcss:
  cache: false
